### ISSUE TITLE
Search / Algolia Reusable Component

### ISSUE THREAD

**Issue by w0251251** [w0251251/Rep-ai-graphql#4]
We need a reusable search component that displays the results in a list from a text input using algolia

**Comment by jaruserickson** [comment]
completed: example below as to execution
```
<SingleSearchComponent
        type={'UsernameSearch'}
        renderItem={(props) => (
            <RenderUser {...props} />
        )}
        navigation={this.props.navigation}
        placeholder={'Users'}
/>
```
 - `type` is the index from algolia/graphcool
- `renderItem` is the jsx component used to render each component, props are passed down from algolia. the search item's id is by default a prop passed down.
- `navigation` is simply the navigation that should be passed down
- `placeholder` is the placeholder in the search bar i.e. 'Search for Users'

if you're having any problems feel free to let me know or open another issue
